version: "3.7"
services:
    db:
        image: postgres:15
        container_name: foton_db
        command: -p 5432
        expose:
            - 5432
        env_file:
            - .env

    app:
        build:
            context: .
        env_file:
            - .env
        container_name: foton_app
        command: ["/fastapi_app/docker/app.sh"]
        ports:
            - 9999:8000
        depends_on:
            - db